function [fitresult, gof] = createFit(activeCasesSinceFeb15_2020)
%CREATEFIT(ACTIVECASESSINCEFEB15_2020)
%  Create a fit.
%
%  Data for 'untitled fit 8' fit:
%      Y Output: activeCasesSinceFeb15_2020 from A
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Dec-2022 17:32:25


%% Fit: 'untitled fit 8'.
[xData, yData] = prepareCurveData( [], activeCasesSinceFeb15_2020 );

% Set up fittype and options.
ft = fittype( 'gauss8' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [17994337 716 12.2513321590171 10401195.4235531 699 15.2826437106569 10086453.4140276 735 17.7885544452192 7035655 338 19.667242110981 5159532.64801057 303 29.8292841973608 5074804 582 23.7306653121092 4189580.48832681 369 40.6614754350129 4126136 897 41.019109741328];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 8' );
h = plot( fitresult, xData, yData );
legend( h, 'activeCasesSinceFeb15_2020', 'untitled fit 8', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
ylabel( 'activeCasesSinceFeb15_2020', 'Interpreter', 'none' );
grid on


